### ISSUE TITLE
toDate of any string returns a date value instead of null as per the specification

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#112]
`toDate("abcd")` returns -25598.223032407408. It should return null ideally as per the [spec](https://opensource.adobe.com/json-formula/doc/output/json-formula-specification-1.0.2.html#_todate)

**Comment by JohnBrinkman** [comment]
Fixed with https://github.com/adobe/json-formula/commit/ebc14adfc35b134f29482b1ddda63f93dd8633bf
