### ISSUE TITLE
Incorrect return description for eomonth

### ISSUE THREAD

**Issue by Eswcvlad** [adobe/json-formula#126]
> Returns
> integer - the number of days in the computed month

In reality it returns a date/time value (i.e. number), which corresponds to the start of the last day of the month. Which makes sense, based on the name. :)

Not quite sure, how to write it in a non-confusing way. In the Excel docs they have:

> Returns the serial number for the last day of the month that is the indicated number of months before or after start_date.

Which also doesn't seem right...

**Comment by JohnBrinkman** [comment]
I updated the description of the return value when I was looking at the integer/date handling.
It now says:

> @return {number} the date of the last day of the month
