### ISSUE TITLE
Error type in mod

### ISSUE THREAD

**Issue by Eswcvlad** [adobe/json-formula#154]
Currently `mod` throws FunctionError, if `divisor` is 0.

Maybe it would be better to throw an EvaluationError instead? This is what currently happens in other math functions (`power`, `log`, `log10`, `sqrt`, ...) and would be consistent with division outside of functions as well.

---

_Don't think I have anything left to report. I have some type coercion stuff with sum types left, but I am not sure it makes sense to bring them up after #146._

**Comment by JohnBrinkman** [comment]
agreed
