### ISSUE TITLE
Unexpected "fromEntries" result with `null`

### ISSUE THREAD

**Issue by Eswcvlad** [adobe/json-formula#160]
In the implementation we have this:

- ``fromEntries(`null`)`` -> `TypeError`
- ``fromEntries(`[]`)`` -> `{}`

Based on the spec, these cases should be equivalent and return `{}`.

**Comment by JohnBrinkman** [comment]
The implementation won't coerce a `null` to an array-of-arrays, but will coerce an empty array to an array-of-arrays.
I'll change the implementation to explicitly allow an empty array.
