### ISSUE TITLE
power() function or ^ operator

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#23]
We need to decide whether we want the power function or the ^ operator. Currently we support both of them.

I propose removal of the operator

**Comment by JohnBrinkman** [comment]
I agree. Power is infrequently used in forms, so one less operator is good.

**Comment by JohnBrinkman** [comment]
I am at peace with removing the `^` operator.  Not only do we have the power() function -- but the use of the caret operator isn't consistent between languages.  e.g. in JS, the caret operator is a bitwise XOR operator.  JS uses `**` for power.
