### ISSUE TITLE
Escaping ` in literals.

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#24]
The antlr grammar allows the following expression 
```
`["abc`def"]`
```
and the autogenerated parser generates the following AST
```
(formula (expression (literal ` (jsonValue "abc`def") `)) <EOF>)
```

But our parser throws an exception since we do not support **`** inside literals. It must be escaped, i.e the expression below is correct as per our parser

```
`["abc\`def"]`
```

Either we update the antlr grammar or update the parser to resolve that ambiguity

**Comment by JohnBrinkman** [comment]
Note that we have not changed this behavior.  This problem is inherited from the JMESPath implementation.
It looks to me like this would be best fixed at the grammar level.  But we need to make sure that other nested quote scenarios work.  e.g. ``['abc`def']`` should be valid.

**Comment by JohnBrinkman** [comment]
@vdua I think this is now fixed with https://github.com/adobe/json-formula/commit/83d9dbb912a3d44680c4b0316a604a14d4c665fe
Can you check?

**Comment by vdua** [comment]
Verified. Marking it as fixed.
