### ISSUE TITLE
Node Version required for JSON Formula

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#33]
We mention that node version required is >= 10.0 but we use String.prototype.replaceAll function which requires node >=15

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility

**Comment by JohnBrinkman** [comment]
fixed with https://github.com/adobe/json-formula/commit/cf1ae0358125c5114017b79ef36bd11d911c957b
