### ISSUE TITLE
Min Function in the library

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#46]
min function is present both in jmespath and openformula but with different syntax.

The jmespath version takes an array of elements
`min([1, 2, 3])`

while the openformula version takes varargs
`MIN(1, 2, 3)`

Should we support both ?

**Comment by JohnBrinkman** [comment]
Hmm.  Looking at this again, it looks like Excel allows any of the arguments to be ranges and then will find the minimum inside the ranges.  I suppose we should to the same -- allow arrays where excel allows ranges.
So `min([3,4,5], [1,2,3], -2)` would return `-2` and `min([3,4,5], [1,2,3], 2) ` would return `1`

**Comment by JohnBrinkman** [comment]
We'd need to do the same for `max()`.

**Comment by vdua** [comment]
Resolved
