### ISSUE TITLE
The expression "123 Avenue Road" + 4 returns 127

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#5]
Since we use `parseFloat` to convert string to numbers, which leads to this unexpected behaviour

### Expected Behaviour

"123 Avenue Road" + 4 should equal 4

### Actual Behaviour

"123 Avenue Road" + 4 returns 127

#### Steps to Reproduce

Write the expression 
"123 Avenue Road" + 4  in the playground (https://opensource.adobe.com/json-formula/dist/index.html) and the wrong result appears on the right.

The PR https://github.com/vdua/json-formula/pull/1 fixes that. Will add test cases and raise a PR here as well.

More details on how https://stackoverflow.com/questions/17106681/parseint-vs-unary-plus-when-to-use-which/17106702

**Comment by MatthiasValvekens** [comment]
> "123 Avenue Road" + 4 should equal 4

Maybe this is a stupid question, but why should this equal `4`? If implicit coercion is preferred to just throwing a type error, I would expect the non-string arguments to be stringified, and for this to reduce to `"123 Avenue Road4"` rather than `4`.

**Comment by vdua** [comment]
`+` operator is for numbers while for string we have the `&` operator. I was going with the current implementation where
'Avenue Road' + 4` returns `4` as per the current rules.

I would wait for @JohnBrinkman to give his thoughts on the same. 

The type coercion rule for toNumber are (for different data types) as per the current code

string -> parseFloat(number), and if it fails then, 0
null/Array-> 0
boolean -> 0 if false, 1 if true
object -> exception

**Comment by JohnBrinkman** [comment]
@vdua I agree that the current behavior is not correct.  But I think we need to look at the openformula to define the correct behavior.  It would use the `value()` function to convert to number.  It would successfully convert strings such as "$123", "12%" and "12/24/2003" to numbers.
https://www.oasis-open.org/committees/download.php/16826/openformula-spec-20060221.html#VALUE

**Comment by MatthiasValvekens** [comment]
Ah, right, if we already have a perfectly good operator for string concatenation and `+` is math-only, then I suppose coercing mixed arguments to `+` to strings doesn't make a lot of sense.

Thanks for the input!

**Comment by vdua** [comment]
@JohnBrinkman @MatthiasValvekens
Have been doing some homework on this and I feel auto type conversion to numbers may not work uniformly. If a field is not a number or not an array of numbers the + operator should return null (or isNaN which can be converted to null). 

We may need conversion from null to numbers (by defining Value(null) === 0) to take care of empty values, though it can be handled by the Forms Runtime in most cases. I think we can leave it to Forms Author to use the correct operators (can be taken care by authoring UI as well) and do type conversion using the well defined functions.

**Comment by JohnBrinkman** [comment]
@vdua I don't think we can remove all type coercion from the language -- especially since it happens in both JavaScript and OpenFormula.
e.g. the expression `4 * '2'` should always return `8`.
To me, the question is one of how aggressively we perform type coercion.  Maybe we don't try to auto-convert date strings and currencies?
Maybe you can share where you see inconsistencies?

**Comment by JohnBrinkman** [comment]
Recommendation is that we mimic the way Excel and openformula coerce values in the `VALUE()` function.
This means attempting to do a locale-sensitive conversion of date and currency values to numbers.
Beyond that we will use the default JavaScript conversion of string to number (no longer using `parseFloat()`.  
The json-formula API is enhanced to allow an application to provide a locale-sensitive `stringToNumber()` function.
