### ISSUE TITLE
Retire maxBy(), minBy()

### ISSUE THREAD

**Issue by JohnBrinkman** [adobe/json-formula#52]
With the addition of the `reduce()` function, `maxBy()` and `minBy()` can be made redundant.
e.g. given this data:

```
{
  "people": [
    {"age": 10, "name": "Joe"},
    {"age": 20, "name": "John"},
    {"age": 30, "name": "Mary"},
    {"age": 40, "name": "Frank"},
    {"age": 50, "name": "Ed"}
  ]
}
```

The oldest person can be found by:

`maxBy(people, &age)`

or by:

`reduce(&max([@.accumulated, @.current]), people, people[0].age)`

Next release this can be simplified slightly to:

`reduce(&max(@.accumulated, @.current), people, people[0].age)`

**Comment by vdua** [comment]
Resolved
