### ISSUE TITLE
Should we use a 'big number' library?

### ISSUE THREAD

**Issue by JohnBrinkman** [adobe/json-formula#7]
JavaScript has rounding issues. e.g. 
```
10 * 1.44
14.399999999999999
```

There are JS packages available to help with this problem:
https://www.npmtrends.com/big-number-vs-big.js-vs-bignumber.js-vs-decimal.js-vs-decimal.js-light

**Comment by JohnBrinkman** [comment]
We should incorporate a big number library and leave a note in the spec to recommend this for JS implementations.
(But we don't mandate a big number library)

**Comment by iamrahulrnair** [comment]
Hi there, I would love to collaborate, and this seems new to me, can you suggest some references for me to get to know more about this project, thanks

**Comment by iamrahulrnair** [comment]
Hey john, Hope this issue still active

**Comment by JohnBrinkman** [comment]
@iamrahulrnair Yes, the issue is active.  We're doing some investigation to see which big number library to use.  Then we'll incorporate.  Do you have a preferred package?

**Comment by iamrahulrnair** [comment]
> @iamrahulrnair Yes, the issue is active. We're doing some investigation to see which big number library to use. Then we'll incorporate. Do you have a preferred package?

uhh no at the moment, i will check on that, to work on this project do i need any prior experience regarding any other projects , if so could you tell where i need to refer, i wud love to collaborate in this project :-)

**Comment by JohnBrinkman** [comment]
Rahul: We would welcome pull requests from any contributors.  If you'd like to tackle this issue, then I suggest you write a brief proposal on the implementation.  If the proposal is agreeable, then we could assign the issue to you.

**Comment by iamrahulrnair** [comment]
> @iamrahulrnair Yes, the issue is active. We're doing some investigation to see which big number library to use. Then we'll incorporate. Do you have a preferred package?

uhh no at the moment, i will check on that, to work on this project do i need any prior experience regarding any other projects , if so could you tell where i need to refer, i wud love to collaborate in this project :-)

**Comment by JohnBrinkman** [comment]
I think we're at peace with having regular precision -- and documenting the potential problems
