### ISSUE TITLE
Make the parser throw error on invalid strings inside JSON Literals

### ISSUE THREAD

**Issue by vdua** [adobe/json-formula#70]
The JSON Formula Parser supports any character after the escape character inside JSON Stings. i.e. as per parser the string below is a valid json string but as per the standards it is not. The antlr grammar also throws an error for this particular string but 
the parser succeeds
```
`"\\z"`
``` 
See the discussion around the issue
https://github.com/adobe/json-formula/pull/67#discussion_r1318058758

### Expected Behaviour
The parser should be strict and throw an error for these strings

**Comment by JohnBrinkman** [comment]
fixed with https://github.com/adobe/json-formula/pull/86
