### ISSUE TITLE
Miscellaneous expression issues

### ISSUE THREAD

**Issue by JohnBrinkman** [adobe/json-formula#75]
## issue 1
```
merge({w:2}, {q:3}, "82")
returns:
{
  "0": "8",
  "1": "2",
  "w": 2,
  "q": 3
}
```

It should just omit the string from the result and return:
```
{
  "w": 2,
  "q": 3
}
```

## issue 2
`[1,2] ~ {w:1}` gives an error.
Whereas `[1,2] ~ 3` gives `[1,2,3]`
`[1,2] ~ {w:1}` should give: `[1,2,{"w":1}]`

## issue 3
According to https://github.com/adobe/json-formula/issues/5 we were going to support limited date-to-number conversions
But it doesn't look like we do?  Maybe we should attempt to convert whatever the date constructor allows?
With the caveat that the results are locale-specific (same sort of warnings we get from the date constructor docs)

## issue 4
Divide by zero returns null without any error or warning.  We should at least emit a warning.

**Comment by vdua** [comment]
### issue 5
Identifier with escaped single quote `'` doesn't work. If you have the object `{"quote'char": "value"}` then accessing the value of `"quote'char"` via the expression `'quote\'char'` throws an error.

**Comment by vdua** [comment]
> [1,2] ~ {w:1} should give: [1,2,{"w":1}]

This is not supported explicitly as per the [comment](https://github.com/adobe/json-formula/blob/009c13c19001f1599b2abc0ad3b2307ce3a642ba/src/jmespath/matchType.js#L84) 
> // Can't coerce Objects to any other type,

**Comment by vdua** [comment]
Also for divide by 0, I think we should throw an exception along the lines of open formula
<img width="489" alt="image" src="https://github.com/adobe/json-formula/assets/2097597/ac3fc525-4013-4110-8199-25effafe9531">

**Comment by JohnBrinkman** [comment]
## Issue 7
Some combinations of wildcard syntax do not parse correctly:

These cases fail:

* `A * *` (First Asterix is multiplication. Second is a wildcard). Shortcut for: `A * @.*` -- which works)
* `!*`  (`!@.*` works)
* `(*)` (`(*)` works)

**Comment by JohnBrinkman** [comment]
All issues fixed
